---
- include_tasks: install-borg.yml
  tags:
    - install-borg

- include_tasks: cronitor.yml
  when: cronitor.enabled

- include_tasks: ssh.yml
  tags:
    - ssh

- include_tasks: borg.yml
  tags:
    - borg

- include_tasks: nextcloud.yml
  when: nextcloud_enabled
  tags:
    - nextcloud
