---

- include: install-borg.yml
  tags:
    - install-borg

- include: ssh.yml
  tags:
    - ssh
      
- include: borg.yml
  tags:
    - borg

- include: nextcloud.yml
  when: nextcloud_enabled
  tags:
    - nextcloud
