---
- name: nextcloud | Add nextcloud.sh to backup scripts folder
  template:
    src: nextcloud.sh.j2
    dest: "{{backup_user_home}}/backup-nextcloud.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: "0700"

- name: nextcloud | Nextcloud Cron Entry
  cron:
    name: "Run backup script for nextcloud"
    minute: "{{ nextcloud_cron_minute }}"
    hour: "{{ nextcloud_cron_hour }}"
    day: "{{ nextcloud_cron_day }}"
    weekday: "{{ nextcloud_cron_weekday }}"
    month: "{{ nextcloud_cron_month }}"
    job: "{{backup_user_home}}/backup-nextcloud.sh"
    cron_file: "{{ cron_file }}"
    user: "{{ backup_user }}"
  when: cron_enabled
