---
restic_path: /usr/bin/restic
restic_install: false
restic_user: root
restic_user_home: /root
restic_repositories: []
restic_forget: true
restic_prune: true
restic_check: true

restic_ssh_host: backup
restic_ssh_port: 22
restic_ssh_private_key_path: /root/.ssh/backup

nextcloud_db: nextcloud
nextcloud_db_user: nextcloud
