---
- hosts: all
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/nextcloud.yml
      when: nextcloud_enabled
    - import_tasks: tasks/borg.yml
      when: borg
    - import_tasks: tasks/restic.yml
      when: restic
    
