---
version: "3"

vars:
  ANSIBLE_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_INVENTORY_DIR: "{{.ANSIBLE_DIR}}/inventory"
  ANSIBLE_PLAYBOOK_DIR: "{{.ANSIBLE_DIR}}/playbooks"

env:
  ANSIBLE_CONFIG: "{{.ANSIBLE_DIR}}/ansible.cfg"

tasks:
  backup-install:
    desc: Install backup scripts on all hosts
    cmds:
      - "ansible-playbook -i {{.ANSIBLE_INVENTORY_DIR}}/coffee-shop/hosts.yml {{.ANSIBLE_PLAYBOOK_DIR}}/install.yaml"
    silent: true

  backup-status:
    desc: Get the status of all backups
    cmds:
      - "ansible cappuccino -a '/root/backup-cappuccino-status.sh' -K"
      - "ansible cappuccino -a '/root/backup-photos-status.sh' -K"
      - "ansible mocha -a '/root/backup-mocha-status.sh' -K"
    silent: true
