---
- name: Add nextcloud.sh to backup scripts folder
  template:
    src: nextcloud.sh.j2
    dest: '{{backup_user_home}}/backup-nextcloud.sh'
    owner: '{{ backup_user }}'
    group: '{{ backup_user }}'
    mode: '0700'

- name: Nextcloud Cron Entry
  cron:
    name: "Run backup script for nextcloud"
    minute: "{{ cron_minute }}"
    hour: "{{cron_hour}}"
    day: "{{cron_day}}"
    weekday: "{{cron_weekday}}"
    month: "{{cron_month}}"
    job: "{{backup_user_home}}/backup-nextcloud.sh"
    cron_file: "{{ cron_file }}"
    user: "{{ backup_user }}"
  when: cron_enabled
