---
- name: Add nextcloud.sh to backup scripts folder
  template:
    src: nextcloud.sh.j2
    dest: '{{restic_user_home}}/backup-nextcloud.sh'
    owner: '{{ restic_user }}'
    group: '{{ restic_user }}'
    mode: '0700'
