---
- name: Create restic backup scripts
  template:
    src: restic-backup.sh.j2
    dest: '{{backup_user_home}}/backup-{{ item.name }}-auto.sh'
    mode: '0700'
    owner: '{{backup_user}}'
    group: '{{backup_user}}'
  vars:
    restic_repository: '{{item}}'
  loop: '{{restic_repositories.values() | list}}'

- name: Cron Restic Entires
  cron:
    name: "Run backup script for {{ item.name }}"
    minute: "{{ cron_minute }}"
    hour: "{{cron_hour}}"
    day: "{{cron_day}}"
    weekday: "{{cron_weekday}}"
    month: "{{cron_month}}"
    job: "{{backup_user_home}}/backup-{{item.name}}-auto.sh"
    cron_file: "{{ cron_file }}"
  when: cron_enabled
  loop: '{{ restic_repositories.values() | list }}'
